QUESTION_TYPE_TO_SKILL_TAG = {
    'DEFINITION_MC_SINGLE': 'definition_recall',
    'DEFINITION_TRUE_FALSE': 'definition_recall',
    'DEFINITION_MATCHING': 'definition_recall',
    'CONTEXT_MC_SINGLE': 'context_nuance',
    'CONTEXT_FILL_IN_BLANK': 'context_nuance',
    'CONNOTATION_SORTING': 'context_nuance',
    'SYNONYM_MC_SINGLE': 'synonym_antonym',
    'SYNONYM_MC_MULTI': 'synonym_antonym',
    'SYNONYM_MATCHING': 'synonym_antonym',
    'ANTONYM_MC_SINGLE': 'synonym_antonym',
    'ANTONYM_MATCHING': 'synonym_antonym',
    'ODD_ONE_OUT_MC_SINGLE': 'synonym_antonym',
    'WORD_FORM_MC': 'word_forms',
    'WORD_FORM_FILL_IN_BLANK': 'word_forms',
    'SENTENCE_SCRAMBLE': 'syntax_grammar',
    'DIALOGUE_COMPLETION_MC': 'context_nuance',
    'SPELLING_FILL_IN_BLANK': 'spelling',
    'COLLOCATION_MC_SINGLE': 'collocation_usage',
    'COLLOCATION_FILL_IN_BLANK': 'collocation_usage',
    'COLLOCATION_MATCHING': 'collocation_usage',
    'CONCEPTUAL_ASSOCIATION_MC_SINGLE': 'conceptual_association',
}

QUESTION_TYPE_TO_PATTERN = {
    'DEFINITION_MC_SINGLE': 'Definition Recall',
    'DEFINITION_TRUE_FALSE': 'Definition Recall',
    'CONTEXT_MC_SINGLE': 'Context & Nuance',
    'SYNONYM_MC_SINGLE': 'Synonym & Antonym',
    'ANTONYM_MC_SINGLE': 'Synonym & Antonym',
    'WORD_FORM_MC': 'Word Forms',
    'WORD_FORM_FILL_IN_BLANK': 'Word Forms',
    'SENTENCE_SCRAMBLE': 'Syntax & Grammar',
    'DIALOGUE_COMPLETION_MC': 'Context & Nuance',
    'SPELLING_FILL_IN_BLANK': 'Spelling',
    'CONTEXT_FILL_IN_BLANK': 'Context & Nuance',
    'COLLOCATION_MC_SINGLE': 'Collocation & Usage',
    'ODD_ONE_OUT_MC_SINGLE': 'Synonym & Antonym',
    'CONCEPTUAL_ASSOCIATION_MC_SINGLE': 'Conceptual Association',
}
