"""Pipeline steps 7-8: Graphic Novel Script and Images.

This module is a thin facade that re-exports the implementation now split
across `graphic_novel_helpers`, `graphic_novel_validators`,
`graphic_novel_script`, and `graphic_novel_images`. External callers and
tests can keep importing from this path unchanged.
"""
from vocabulary.services.generation.graphic_novel_helpers import (
    CHAR_INK_COLORS,
    SECONDARY_CHARACTER_ANCHOR_TEMPLATE_PATH,
    _characters_for_graphic_novel_page,
    _count_direct_ink_uses,
    _expected_page_count_from_summary,
    _find_secondary_characters_needing_anchors,
    _format_anchor_design_lock,
    _format_character_name_colors,
    _format_characters_for_image_prompt,
    _format_graphic_novel_prompt,
    _format_graphic_novel_setting_context,
    _format_panels_as_prose,
    _format_synopsis_for_page,
    _format_vocab_details_for_review,
    _format_vocab_highlighting,
    _generate_secondary_character_anchors,
    _graphic_novel_artifact_dir,
    _graphic_novel_artifact_summary,
    _graphic_novel_word_summary,
    _lexi_legends_age_band,
    _load_substep_artifact,
    _log_graphic_novel_substep,
    _page_vocab_words,
    _run_graphic_novel_substep,
    _target_terms_from_input,
    _text_terms_from_graphic_novel_page,
    _write_graphic_novel_artifact,
)
from vocabulary.services.generation.graphic_novel_images import (
    _step_graphic_novel_images,
)
from vocabulary.services.generation.graphic_novel_script import (
    _step_graphic_novel_script,
    restart_graphic_novel_from_substep,
)
from vocabulary.services.generation.graphic_novel_validators import (
    SubstepContext,
    _validate_beat_complexity,
    _validate_graphic_novel_beat_result,
    _validate_graphic_novel_cloze_result,
    _validate_graphic_novel_router_result,
    _validate_graphic_novel_scoring_result,
    _validate_graphic_novel_script_result,
    _validate_graphic_novel_team_result,
    _validate_vocab_anchors,
    _validate_vocab_integration_plan,
    _validate_words_data_covers_pack,
)

__all__ = [
    'CHAR_INK_COLORS',
    'SECONDARY_CHARACTER_ANCHOR_TEMPLATE_PATH',
    'SubstepContext',
    '_characters_for_graphic_novel_page',
    '_count_direct_ink_uses',
    '_expected_page_count_from_summary',
    '_find_secondary_characters_needing_anchors',
    '_format_anchor_design_lock',
    '_format_character_name_colors',
    '_format_characters_for_image_prompt',
    '_format_graphic_novel_prompt',
    '_format_graphic_novel_setting_context',
    '_format_panels_as_prose',
    '_format_synopsis_for_page',
    '_format_vocab_details_for_review',
    '_format_vocab_highlighting',
    '_generate_secondary_character_anchors',
    '_graphic_novel_artifact_dir',
    '_graphic_novel_artifact_summary',
    '_graphic_novel_word_summary',
    '_lexi_legends_age_band',
    '_load_substep_artifact',
    '_log_graphic_novel_substep',
    '_page_vocab_words',
    '_run_graphic_novel_substep',
    '_step_graphic_novel_images',
    '_step_graphic_novel_script',
    '_target_terms_from_input',
    '_text_terms_from_graphic_novel_page',
    '_validate_beat_complexity',
    '_validate_graphic_novel_beat_result',
    '_validate_graphic_novel_cloze_result',
    '_validate_graphic_novel_router_result',
    '_validate_graphic_novel_scoring_result',
    '_validate_graphic_novel_script_result',
    '_validate_graphic_novel_team_result',
    '_validate_vocab_anchors',
    '_validate_vocab_integration_plan',
    '_validate_words_data_covers_pack',
    '_write_graphic_novel_artifact',
    'restart_graphic_novel_from_substep',
]
