# Generated by Django 5.2.7 on 2026-02-27 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The top-level program or series, e.g., "Wonders Reading".', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The grade or difficulty level, e.g., "Grade 2".', max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='An integer for sorting.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasteryLevel',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=50)),
                ('interval_days', models.IntegerField(help_text='Days to wait for next review at this level')),
                ('points_to_promote', models.IntegerField(help_text='Points needed to graduate from this level')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('FULL_PIPELINE', 'Full Pipeline'), ('QUESTIONS_ONLY', 'Questions Only'), ('INSTRUCTIONAL_ONLY', 'Instructional Only')], default='FULL_PIPELINE', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=30)),
                ('input_words', models.JSONField(help_text='Raw word list from teacher')),
                ('input_source_title', models.CharField(blank=True, default='', max_length=300)),
                ('input_source_chapter', models.CharField(blank=True, default='', max_length=300)),
                ('input_source_text', models.TextField(blank=True, default='')),
                ('target_lexile', models.IntegerField(default=650)),
                ('target_language', models.CharField(choices=[('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('es', 'Spanish'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('fr', 'French')], default='zh-CN', max_length=10)),
                ('words_created', models.IntegerField(default=0)),
                ('questions_created', models.IntegerField(default=0)),
                ('primer_cards_created', models.IntegerField(default=0)),
                ('stories_created', models.IntegerField(default=0)),
                ('cloze_items_created', models.IntegerField(default=0)),
                ('images_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('WORD_LOOKUP', 'Word Lookup'), ('DEDUP', 'Deduplication'), ('TRANSLATION', 'Translation'), ('QUESTION_GEN', 'Question Generation'), ('PACK_CREATION', 'Pack Creation'), ('PRIMER_GEN', 'Primer Generation'), ('STORY_CLOZE_GEN', 'Story & Cloze Generation'), ('IMAGE_GEN', 'Image Generation')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=30)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vocabulary.generationjob')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('DEFINITION_MC_SINGLE', 'Definition MC (Single Ans)'), ('DEFINITION_TRUE_FALSE', 'Definition True/False'), ('DEFINITION_MATCHING', 'Definition Matching'), ('SYNONYM_MC_SINGLE', 'Synonym MC (Single Ans)'), ('SYNONYM_MC_MULTI', 'Synonym MC (Multi Ans)'), ('SYNONYM_MATCHING', 'Synonym Matching'), ('ANTONYM_MC_SINGLE', 'Antonym MC (Single Ans)'), ('ANTONYM_MATCHING', 'Antonym Matching'), ('CONTEXT_MC_SINGLE', 'Context MC (Single Ans)'), ('CONTEXT_FILL_IN_BLANK', 'Context Fill-in-Blank'), ('SPELLING_FILL_IN_BLANK', 'Spelling Fill-in-Blank'), ('WORD_FORM_FILL_IN_BLANK', 'Word Form Fill-in-Blank'), ('WORD_FORM_MC', 'Word Form MC'), ('SENTENCE_SCRAMBLE', 'Sentence Scramble'), ('ODD_ONE_OUT_MC_SINGLE', 'Odd One Out MC (Single Ans)'), ('CONNOTATION_SORTING', 'Connotation Sorting'), ('COLLOCATION_MC_SINGLE', 'Collocation MC (Single Ans)'), ('COLLOCATION_FILL_IN_BLANK', 'Collocation Fill-in-Blank'), ('COLLOCATION_MATCHING', 'Collocation Matching'), ('CONCEPTUAL_ASSOCIATION_MC_SINGLE', 'Conceptual Association MC (Single Ans)')], max_length=50)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answers', models.JSONField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('example_sentence', models.TextField(blank=True, default='', help_text='A sentence demonstrating the word usage in context.')),
                ('lexile_score', models.IntegerField(blank=True, help_text='The estimated Lexile score for the question text.', null=True)),
                ('difficulty_index', models.FloatField(blank=True, help_text='P-Value: Proportion of users who answered correctly.', null=True)),
                ('discrimination_index', models.FloatField(blank=True, help_text='How well the question differentiates high/low-performing users.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='vocabulary.generationjob')),
                ('suitable_levels', models.ManyToManyField(blank=True, related_name='questions', to='vocabulary.masterylevel')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Time in seconds taken to answer', null=True)),
                ('answer_switches', models.IntegerField(default=0, help_text='Number of times the user changed their answer before submitting.')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocabulary.question')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocabulary.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100)),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=50)),
                ('source_context', models.CharField(blank=True, default='', help_text='e.g., "From the book Cosmos"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='words', to='vocabulary.tag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocabulary.word'),
        ),
        migrations.CreateModel(
            name='PrimerCardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllable_text', models.CharField(help_text='e.g., "vo·cab·u·la·ry"', max_length=200)),
                ('image_url', models.URLField(blank=True, default='')),
                ('audio_url', models.URLField(blank=True, default='')),
                ('kid_friendly_definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primer_content', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_as_new', to='vocabulary.masterylevel')),
                ('old_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_as_old', to='vocabulary.masterylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_logs', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('prompt_used', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.TextField()),
                ('example_sentence', models.TextField(blank=True, default='')),
                ('lexile_score', models.IntegerField(blank=True, help_text='The estimated Lexile score for this definition and example.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='vocabulary.word')),
            ],
            options={
                'ordering': ['lexile_score'],
            },
        ),
        migrations.CreateModel(
            name='DefinitionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Qwen 2.5 vector (list of floats)')),
                ('model_version', models.CharField(default='qwen2.5-embedding-v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='vocabulary.worddefinition')),
            ],
        ),
        migrations.CreateModel(
            name='MicroStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField(help_text='Target words wrapped in **word** markers')),
                ('reading_level', models.IntegerField(help_text='Lexile score')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='vocabulary.wordpack')),
            ],
            options={
                'ordering': ['reading_level'],
            },
        ),
        migrations.CreateModel(
            name='ClozeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.TextField(help_text='Sentence with _______ blank')),
                ('correct_answer', models.CharField(max_length=200)),
                ('distractors', models.JSONField(help_text='List of 2 distractor strings')),
                ('order', models.IntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_items', to='vocabulary.word')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_items', to='vocabulary.wordpack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book, article, or unit.', max_length=200)),
                ('unit_or_chapter', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_text', models.TextField(blank=True, default='', help_text='Optional passage text for LLM context during generation.')),
                ('is_public', models.BooleanField(default=False, help_text='If true, visible to other teachers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_word_sets', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_sets', to='vocabulary.curriculum')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_sets', to='vocabulary.level')),
                ('words', models.ManyToManyField(blank=True, related_name='word_sets', to='vocabulary.word')),
            ],
        ),
        migrations.AddField(
            model_name='wordpack',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='vocabulary.wordset'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='vocabulary.wordset'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(help_text='The field being translated, e.g. "definition_text", "example_sentence"', max_length=30)),
                ('language', models.CharField(choices=[('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('es', 'Spanish'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('fr', 'French')], max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='vocabulary__content_075623_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_points', models.IntegerField(default=0)),
                ('next_review_date', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('instructional_status', models.CharField(choices=[('READY', 'Ready'), ('PENDING', 'Pending Instruction')], default='READY', max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocabulary.masterylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='vocabulary.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='StudentPackCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_completions', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='vocabulary.wordpack')),
            ],
            options={
                'unique_together': {('user', 'pack')},
            },
        ),
        migrations.CreateModel(
            name='WordPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocabulary.wordpack')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='vocabulary.word')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pack', 'word')},
            },
        ),
        migrations.CreateModel(
            name='StudentWordSetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_word_sets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_set_assignments', to=settings.AUTH_USER_MODEL)),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vocabulary.wordset')),
            ],
            options={
                'unique_together': {('user', 'word_set')},
            },
        ),
    ]
