# Generated by Django 5.2.7 on 2026-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionembedding',
            name='embedding',
            field=models.JSONField(help_text='Vector embedding (list of floats)'),
        ),
        migrations.AlterField(
            model_name='definitionembedding',
            name='model_version',
            field=models.CharField(default='Qwen/Qwen3-Embedding-8B', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('DEFINITION_MC_SINGLE', 'Definition MC (Single Ans)'), ('DEFINITION_TRUE_FALSE', 'Definition True/False'), ('DEFINITION_MATCHING', 'Definition Matching'), ('SYNONYM_MC_SINGLE', 'Synonym MC (Single Ans)'), ('SYNONYM_MC_MULTI', 'Synonym MC (Multi Ans)'), ('SYNONYM_MATCHING', 'Synonym Matching'), ('ANTONYM_MC_SINGLE', 'Antonym MC (Single Ans)'), ('ANTONYM_MATCHING', 'Antonym Matching'), ('CONTEXT_MC_SINGLE', 'Context MC (Single Ans)'), ('CONTEXT_FILL_IN_BLANK', 'Context Fill-in-Blank'), ('SPELLING_FILL_IN_BLANK', 'Spelling Fill-in-Blank'), ('WORD_FORM_FILL_IN_BLANK', 'Word Form Fill-in-Blank'), ('WORD_FORM_MC', 'Word Form MC'), ('SENTENCE_SCRAMBLE', 'Sentence Scramble'), ('DIALOGUE_COMPLETION_MC', 'Dialogue Completion MC'), ('ODD_ONE_OUT_MC_SINGLE', 'Odd One Out MC (Single Ans)'), ('CONNOTATION_SORTING', 'Connotation Sorting'), ('COLLOCATION_MC_SINGLE', 'Collocation MC (Single Ans)'), ('COLLOCATION_FILL_IN_BLANK', 'Collocation Fill-in-Blank'), ('COLLOCATION_MATCHING', 'Collocation Matching'), ('CONCEPTUAL_ASSOCIATION_MC_SINGLE', 'Conceptual Association MC (Single Ans)')], max_length=50),
        ),
    ]
