# Generated by Django 5.2.7 on 2026-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_definitionembedding_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='last_completed_step',
            field=models.CharField(blank=True, default='', help_text='Last pipeline step that completed successfully.', max_length=30),
        ),
        migrations.AddField(
            model_name='wordset',
            name='generation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TO_GENERATE', 'To Generate'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='wordset',
            name='input_source_chapter',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='wordset',
            name='input_source_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='wordset',
            name='input_words',
            field=models.JSONField(blank=True, help_text='Raw word list entered by teacher, pending generation.', null=True),
        ),
        migrations.AddField(
            model_name='wordset',
            name='target_lexile',
            field=models.IntegerField(default=650, help_text='Target Lexile reading level.'),
        ),
    ]
