# Generated by Django 5.2.7 on 2026-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_generationjob_last_completed_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='generated_images/'),
        ),
    ]
