# Generated by Django 5.2.7 on 2026-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_generated_image_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpack',
            name='text_type',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('narrative_nonfiction', 'Narrative Non-Fiction')], default='fiction', max_length=30),
        ),
    ]
