# Generated by Django 5.2.7 on 2026-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_add_text_type_to_wordpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjoblog',
            name='step',
            field=models.CharField(choices=[('WORD_LOOKUP', 'Word Lookup'), ('DEDUP', 'Deduplication'), ('TRANSLATION', 'Translation'), ('QUESTION_GEN', 'Question Generation'), ('PACK_CREATION', 'Pack Creation'), ('PRIMER_GEN', 'Primer Generation'), ('STORY_CLOZE_GEN', 'Story & Cloze Generation'), ('IMAGE_GEN', 'Image Generation'), ('PICTURE_MATCH_GEN', 'Picture-Word Match Generation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('DEFINITION_MC_SINGLE', 'Definition MC (Single Ans)'), ('DEFINITION_TRUE_FALSE', 'Definition True/False'), ('DEFINITION_MATCHING', 'Definition Matching'), ('SYNONYM_MC_SINGLE', 'Synonym MC (Single Ans)'), ('SYNONYM_MC_MULTI', 'Synonym MC (Multi Ans)'), ('SYNONYM_MATCHING', 'Synonym Matching'), ('ANTONYM_MC_SINGLE', 'Antonym MC (Single Ans)'), ('ANTONYM_MATCHING', 'Antonym Matching'), ('CONTEXT_MC_SINGLE', 'Context MC (Single Ans)'), ('CONTEXT_FILL_IN_BLANK', 'Context Fill-in-Blank'), ('SPELLING_FILL_IN_BLANK', 'Spelling Fill-in-Blank'), ('WORD_FORM_FILL_IN_BLANK', 'Word Form Fill-in-Blank'), ('WORD_FORM_MC', 'Word Form MC'), ('SENTENCE_SCRAMBLE', 'Sentence Scramble'), ('DIALOGUE_COMPLETION_MC', 'Dialogue Completion MC'), ('ODD_ONE_OUT_MC_SINGLE', 'Odd One Out MC (Single Ans)'), ('CONNOTATION_SORTING', 'Connotation Sorting'), ('COLLOCATION_MC_SINGLE', 'Collocation MC (Single Ans)'), ('COLLOCATION_FILL_IN_BLANK', 'Collocation Fill-in-Blank'), ('COLLOCATION_MATCHING', 'Collocation Matching'), ('CONCEPTUAL_ASSOCIATION_MC_SINGLE', 'Conceptual Association MC (Single Ans)'), ('PICTURE_WORD_MATCH', 'Picture-Word Match')], max_length=50),
        ),
    ]
