# Generated by Django 5.2.7 on 2026-04-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_add_new_question_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSetBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_set_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='vocabulary.wordset')),
            ],
            options={
                'unique_together': {('user', 'word_set')},
            },
        ),
    ]
