# Generated by Django 5.2.7 on 2026-04-05 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_add_word_set_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordset',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='generation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TO_GENERATE', 'To Generate'), ('GENERATION_REQUESTED', 'Generation Requested'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated')], default='DRAFT', max_length=20),
        ),
    ]
