# Generated by Django 5.2.7 on 2026-04-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_add_generation_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='The program this level belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='vocabulary.curriculum'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(help_text='The grade or difficulty level, e.g., "Grade 2".', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('curriculum', 'name')},
        ),
    ]
