# Generated by Django 5.2.7 on 2026-04-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0011_backfill_picture_word_match_lexile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of scaffolded retry attempts after the initial wrong answer.'),
        ),
    ]
