# Generated by Django 5.2.7 on 2026-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0014_adaptive_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image_category',
            field=models.CharField(blank=True, choices=[('EMOTION_STATE', 'Emotion & State'), ('DYNAMIC_ACTION', 'Dynamic Action'), ('INVISIBLE_PROCESS', 'Invisible Process'), ('SENSORY_TRAIT', 'Sensory Trait'), ('SPATIAL_RELATION', 'Spatial Relation'), ('ABSTRACT_METAPHOR', 'Abstract Metaphor'), ('PORTABLE_OBJECT', 'Portable Object'), ('EPIC_SCALE', 'Epic Scale'), ('ICONIC_CHARACTER', 'Iconic Character')], default='', help_text='Visual category for image generation creative direction.', max_length=30),
        ),
    ]
