# Generated by Django 5.2.7 on 2026-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0015_add_image_category_to_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='visual_scene',
            field=models.TextField(blank=True, default='', help_text='LLM-generated visual scene description for image generation.'),
        ),
        migrations.AlterField(
            model_name='generationjoblog',
            name='step',
            field=models.CharField(choices=[('WORD_LOOKUP', 'Word Lookup'), ('DEDUP', 'Deduplication'), ('TRANSLATION', 'Translation'), ('QUESTION_GEN', 'Question Generation'), ('PACK_CREATION', 'Pack Creation'), ('PRIMER_GEN', 'Primer Generation'), ('STORY_CLOZE_GEN', 'Story & Cloze Generation'), ('CREATIVE_DIRECTION', 'Creative Direction'), ('IMAGE_GEN', 'Image Generation'), ('PICTURE_MATCH_GEN', 'Picture-Word Match Generation')], max_length=30),
        ),
    ]
