# Generated by Django 5.2.7 on 2026-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0020_remove_legacy_image_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovelpage',
            name='is_review_page',
            field=models.BooleanField(default=False, help_text='True for the final vocabulary review page'),
        ),
    ]
