# Generated by Django 5.2.7 on 2026-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0021_add_is_review_page_to_graphicnovelpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovel',
            name='characters',
            field=models.JSONField(default=list, help_text='Character visual reference list for cross-page consistency'),
        ),
    ]
