# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0022_graphic_novel_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovel',
            name='metadata',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Lexi Legends metadata: away team, age band, Vault framing, Shades, review artifact',
            ),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='characters_featured',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Canonical character names appearing on this page',
            ),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='is_vault_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='setting_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='vault_zone',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
