# Generated by Django 6.0.5 on 2026-05-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0023_graphic_novel_lexi_legends_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovel',
            name='channel',
            field=models.CharField(choices=[('5page', '5-Page'), ('6page', '6-Page')], default='5page', max_length=10),
        ),
        migrations.AlterField(
            model_name='generationjoblog',
            name='step',
            field=models.CharField(choices=[('WORD_LOOKUP', 'Word Lookup'), ('DEDUP', 'Deduplication'), ('TRANSLATION', 'Translation'), ('QUESTION_GEN', 'Question Generation'), ('PACK_CREATION', 'Pack Creation'), ('PRIMER_GEN', 'Primer Generation'), ('STORY_CLOZE_GEN', 'Story & Cloze Generation'), ('GRAPHIC_NOVEL_SCRIPT', 'Graphic Novel Script'), ('GRAPHIC_NOVEL_IMAGES', 'Graphic Novel Images'), ('GN_6PAGE_SCRIPT', 'Graphic Novel 6-Page Script'), ('GN_6PAGE_IMAGES', 'Graphic Novel 6-Page Images')], max_length=30),
        ),
        migrations.AlterField(
            model_name='graphicnovel',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_novels', to='vocabulary.wordpack'),
        ),
        migrations.AlterUniqueTogether(
            name='graphicnovel',
            unique_together={('pack', 'channel')},
        ),
    ]
