# Generated by Django 6.0.5 on 2026-05-27 16:22

import django.db.models.deletion
from django.db import migrations, models


def seed_defaults(apps, schema_editor):
    LLMSite = apps.get_model('vocabulary', 'LLMSite')
    LLMStepConfig = apps.get_model('vocabulary', 'LLMStepConfig')

    site = LLMSite.objects.create(
        name='Gemini (Default)',
        base_url='',
        api_key_env_var='GEMINI_API_KEY',
        provider_type='gemini_native',
    )

    steps = [
        'word_lookup', 'translation', 'question_gen', 'pack_creation',
        'primer_gen', 'gn_team_selection', 'gn_router_premises',
        'gn_premise_scoring', 'gn_beat_sheet', 'gn_final_script',
    ]
    for step_key in steps:
        LLMStepConfig.objects.create(
            step_key=step_key,
            primary_site=site,
            primary_model='gemini-3.1-pro-preview',
            fallback_site=site,
            fallback_model='gemini-3-pro-preview',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0024_add_graphic_novel_channel_and_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True, default='', help_text='Leave blank for native SDK default endpoint.', max_length=300)),
                ('api_key_env_var', models.CharField(help_text='Environment variable name holding the API key.', max_length=100)),
                ('provider_type', models.CharField(choices=[('gemini_native', 'Gemini (Native)'), ('openai_compatible', 'OpenAI-Compatible'), ('anthropic', 'Anthropic')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Site',
            },
        ),
        migrations.AlterField(
            model_name='graphicnovel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lexi Legends metadata: away team, age band, Vault framing, review artifact'),
        ),
        migrations.CreateModel(
            name='LLMStepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(choices=[('word_lookup', 'Word Lookup'), ('translation', 'Translation'), ('question_gen', 'Question Generation'), ('pack_creation', 'Pack Grouping'), ('primer_gen', 'Primer Generation'), ('gn_team_selection', 'GN: Team Selection'), ('gn_router_premises', 'GN: Router Premises'), ('gn_premise_scoring', 'GN: Premise Scoring'), ('gn_beat_sheet', 'GN: Beat Sheet'), ('gn_final_script', 'GN: Final Script')], max_length=30, unique=True)),
                ('primary_model', models.CharField(max_length=100)),
                ('fallback_model', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallback_steps', to='vocabulary.llmsite')),
                ('primary_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_steps', to='vocabulary.llmsite')),
            ],
            options={
                'verbose_name': 'LLM Step Configuration',
                'verbose_name_plural': 'LLM Step Configurations',
            },
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
