# Generated by Django 6.0.5 on 2026-05-29 15:03

from django.db import migrations, models


def seed_cloze_gen_config(apps, schema_editor):
    LLMSite = apps.get_model('vocabulary', 'LLMSite')
    LLMStepConfig = apps.get_model('vocabulary', 'LLMStepConfig')

    site = LLMSite.objects.first()
    if site and not LLMStepConfig.objects.filter(step_key='gn_cloze_gen').exists():
        LLMStepConfig.objects.create(
            step_key='gn_cloze_gen',
            primary_site=site,
            primary_model='gemini-3.1-pro-preview',
            fallback_site=site,
            fallback_model='gemini-3-pro-preview',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0025_llm_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmstepconfig',
            name='step_key',
            field=models.CharField(choices=[('word_lookup', 'Word Lookup'), ('translation', 'Translation'), ('question_gen', 'Question Generation'), ('pack_creation', 'Pack Grouping'), ('primer_gen', 'Primer Generation'), ('gn_team_selection', 'GN: Team Selection'), ('gn_router_premises', 'GN: Router Premises'), ('gn_premise_scoring', 'GN: Premise Scoring'), ('gn_cloze_gen', 'GN: Cloze Generation'), ('gn_beat_sheet', 'GN: Beat Sheet'), ('gn_final_script', 'GN: Final Script')], max_length=30, unique=True),
        ),
        migrations.RunPython(seed_cloze_gen_config, migrations.RunPython.noop),
    ]
