# Generated by Django 6.0.5 on 2026-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0026_add_gn_cloze_gen_step_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmstepconfig',
            name='step_key',
            field=models.CharField(choices=[('word_lookup', 'Word Lookup'), ('translation', 'Translation'), ('question_gen', 'Question Generation'), ('primer_gen', 'Primer Generation'), ('pack_creation', 'Pack Grouping'), ('gn_team_selection', 'GN: Team Selection'), ('gn_router_premises', 'GN: Router Premises'), ('gn_premise_scoring', 'GN: Premise Scoring'), ('gn_cloze_gen', 'GN: Cloze Generation'), ('gn_beat_sheet', 'GN: Beat Sheet'), ('gn_final_script', 'GN: Final Script')], max_length=30, unique=True),
        ),
    ]
