# Generated by Django 6.0.5 on 2026-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0027_alter_llmstepconfig_step_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovelpage',
            name='edited_image',
            field=models.ImageField(blank=True, help_text='Admin-edited variant of the page image; the original is preserved in `image`.', upload_to='graphic_novels/'),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='use_edited_image',
            field=models.BooleanField(default=False, help_text='When True (and an edited image exists), the edited variant is shown everywhere.'),
        ),
    ]
