# Generated by Django 5.2.7 on 2026-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0028_graphicnovelpage_edited_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovelpage',
            name='edited_image_jpeg',
            field=models.ImageField(blank=True, help_text='Lightweight JPEG companion of `edited_image`, served to students to save bandwidth.', upload_to='graphic_novels/'),
        ),
        migrations.AddField(
            model_name='graphicnovelpage',
            name='image_jpeg',
            field=models.ImageField(blank=True, help_text='Lightweight JPEG companion of `image`, served to students to save bandwidth.', upload_to='graphic_novels/'),
        ),
    ]
