# Generated by Django 5.2.7 on 2026-05-31 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0029_graphicnovelpage_edited_image_jpeg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'answered_at'], name='vocabulary__user_id_a04db8_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='vocabulary__user_id_82e156_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'answered_at'], name='vocabulary__questio_155246_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'next_review_at'], name='vocabulary__user_id_dcfe5f_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'instructional_status'], name='vocabulary__user_id_e04d6a_idx'),
        ),
    ]
