# Generated by Django 6.0.5 on 2026-06-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0031_llm_config_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicNovelPageAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, help_text='Stitched WAV file for the page read-along.', upload_to='graphic_novel_audio/')),
                ('duration_ms', models.IntegerField(default=0)),
                ('voice_manifest', models.JSONField(blank=True, default=dict, help_text='Per-event voice assignments used during generation, for debugging / regen.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='vocabulary.graphicnovelpage')),
            ],
        ),
    ]
