# Generated by Django 6.0.5 on 2026-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0033_audiobook_director_step_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicnovelpageaudio',
            name='audio_mp3',
            field=models.FileField(blank=True, help_text='Compressed MP3 companion of the WAV, served to students.', upload_to='graphic_novel_audio_mp3/'),
        ),
        migrations.AlterField(
            model_name='graphicnovelpageaudio',
            name='audio',
            field=models.FileField(blank=True, help_text='Stitched WAV file for the page read-along (source of truth).', upload_to='graphic_novel_audio/'),
        ),
    ]
