# Generated by Django 6.0.5 on 2026-06-09 17:49

import django.db.models.deletion
from django.db import migrations, models


def select_existing_novels(apps, schema_editor):
    """Existing novels predate candidates: each pack has exactly one, so mark
    it selected (candidate_index already defaults to 0) to keep it student-visible."""
    GraphicNovel = apps.get_model('vocabulary', 'GraphicNovel')
    GraphicNovel.objects.update(is_selected=True)


def deselect_all_novels(apps, schema_editor):
    GraphicNovel = apps.get_model('vocabulary', 'GraphicNovel')
    GraphicNovel.objects.update(is_selected=False)


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0034_graphicnovelpageaudio_audio_mp3_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphicnovel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clozeitem',
            name='novel',
            field=models.ForeignKey(blank=True, help_text='Candidate this cloze was generated for. NULL = promoted/active pack cloze that students practice (set when a candidate is selected). Non-NULL = staged candidate cloze, hidden until its novel is selected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloze_items', to='vocabulary.graphicnovel'),
        ),
        migrations.AddField(
            model_name='graphicnovel',
            name='candidate_index',
            field=models.IntegerField(default=0, help_text='Which generated candidate (0..N-1) this novel is for the pack. Multiple candidates are generated per pack so an admin can pick the best.'),
        ),
        migrations.AddField(
            model_name='graphicnovel',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='True for the one candidate chosen by an admin. Only selected novels are shown to students. No candidate selected = pack not yet published.'),
        ),
        migrations.RunPython(select_existing_novels, deselect_all_novels),
        migrations.AlterField(
            model_name='graphicnovel',
            name='channel',
            field=models.CharField(choices=[('5page', '5-Page'), ('6page', '6-Page')], default='5page', help_text='Vestigial: always "5page". Superseded by candidate_index; kept as a dead column pending removal.', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='graphicnovel',
            unique_together={('pack', 'candidate_index')},
        ),
    ]
