# Generated by Django 6.0.5 on 2026-06-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0035_graphic_novel_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='content_types',
            field=models.JSONField(blank=True, default=list, help_text="Instructional content types to generate, e.g. ['graphic_novel', 'infographic']. Empty/legacy = graphic novel only. A content type's pipeline steps are skipped when it is not listed."),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='infographics_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentwordsetassignment',
            name='content_type',
            field=models.CharField(choices=[('graphic_novel', 'Graphic Novel'), ('infographic', 'Infographic')], default='graphic_novel', help_text='Which instructional content format this student sees for the word set: the graphic novel or the infographic.', max_length=20),
        ),
        migrations.AlterField(
            model_name='clozeitem',
            name='novel',
            field=models.ForeignKey(blank=True, help_text='Graphic novel candidate this cloze was staged for. See the active-set note below.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloze_items', to='vocabulary.graphicnovel'),
        ),
        migrations.AlterField(
            model_name='generationjoblog',
            name='step',
            field=models.CharField(choices=[('WORD_LOOKUP', 'Word Lookup'), ('DEDUP', 'Deduplication'), ('TRANSLATION', 'Translation'), ('QUESTION_GEN', 'Question Generation'), ('PACK_CREATION', 'Pack Creation'), ('PRIMER_GEN', 'Primer Generation'), ('STORY_CLOZE_GEN', 'Story & Cloze Generation'), ('GRAPHIC_NOVEL_SCRIPT', 'Graphic Novel Script'), ('GRAPHIC_NOVEL_IMAGES', 'Graphic Novel Images'), ('INFOGRAPHIC_DESIGN', 'Infographic Design'), ('INFOGRAPHIC_IMAGE', 'Infographic Image'), ('GN_6PAGE_SCRIPT', 'Graphic Novel 6-Page Script'), ('GN_6PAGE_IMAGES', 'Graphic Novel 6-Page Images')], max_length=30),
        ),
        migrations.AlterField(
            model_name='llmstepconfig',
            name='step_key',
            field=models.CharField(choices=[('word_lookup', 'Word Lookup'), ('translation', 'Translation'), ('question_gen', 'Question Generation'), ('primer_gen', 'Primer Generation'), ('pack_creation', 'Pack Grouping'), ('gn_team_selection', 'GN: Team Selection'), ('gn_router_premises', 'GN: Router Premises'), ('gn_premise_scoring', 'GN: Premise Scoring'), ('gn_cloze_gen', 'GN: Cloze Generation'), ('gn_beat_sheet', 'GN: Beat Sheet'), ('gn_final_script', 'GN: Final Script'), ('ig_design', 'Infographic: Design'), ('ig_cloze', 'Infographic: Cloze Generation'), ('audiobook_director', 'Audiobook: Voice Director')], max_length=30),
        ),
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_index', models.IntegerField(default=0, help_text='Which generated candidate (0..N-1) this infographic is for the pack. Multiple candidates are generated so an admin can pick the best.')),
                ('is_selected', models.BooleanField(default=False, help_text='True for the one candidate chosen by an admin. Only selected infographics are shown to students. No candidate selected = not yet published.')),
                ('title', models.CharField(max_length=200)),
                ('intro_text', models.TextField(blank=True, default='', help_text='Short text explaining the infographic, shown to students alongside the image.')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured infographic layout: per-word entries (term, definition, example, visual idea) plus theme/layout notes.')),
                ('style_prompt', models.TextField(blank=True, default='', help_text='Art/design directive used to render the infographic image.')),
                ('reading_level', models.IntegerField(default=650, help_text='Lexile score')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, upload_to='infographics/')),
                ('edited_image', models.ImageField(blank=True, help_text='Admin-edited variant; the original is preserved in `image`.', upload_to='infographics/')),
                ('use_edited_image', models.BooleanField(default=False)),
                ('image_jpeg', models.ImageField(blank=True, help_text='Lightweight JPEG companion of `image`, served to students.', upload_to='infographics/')),
                ('edited_image_jpeg', models.ImageField(blank=True, help_text='Lightweight JPEG companion of `edited_image`, served to students.', upload_to='infographics/')),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generation_attempts', models.IntegerField(default=0)),
                ('generation_error', models.TextField(blank=True, default='')),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infographics', to='vocabulary.wordpack')),
            ],
            options={
                'unique_together': {('pack', 'candidate_index')},
            },
        ),
        migrations.AddField(
            model_name='clozeitem',
            name='infographic',
            field=models.ForeignKey(blank=True, help_text='Infographic candidate this cloze was staged for. See the active-set note below.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloze_items', to='vocabulary.infographic'),
        ),
    ]
