# Generated by Django 6.0.5 on 2026-07-03 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0039_seed_sentence_write_step_configs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userwordprogress',
            name='vocabulary__user_id_e04d6a_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['word', 'lexile_score'], name='vocabulary__word_id_c2be79_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'instructional_status', 'next_review_at'], name='vocabulary__user_id_24e18b_idx'),
        ),
    ]
