# Generated by Django 5.2.7 on 2026-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0040_practice_hot_path_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='primercardcontent',
            name='generated_content_lexile',
            field=models.IntegerField(blank=True, help_text='Content Lexile (job target_lexile x 0.85) this primer was authored at. Rows authored within the reuse window of a later job are kept; NULL predates provenance tracking and is always regenerated.', null=True),
        ),
    ]
