# Generated by Django 5.2.7 on 2026-08-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0041_primercardcontent_generated_content_lexile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('mastery_level_before', models.IntegerField()),
                ('mastery_level_after', models.IntegerField()),
                ('learning_speed_before', models.FloatField()),
                ('learning_speed_after', models.FloatField()),
                ('response_quality_rule', models.CharField(help_text='The schedule_reason string from RESPONSE_QUALITY_RULES classification.', max_length=50)),
                ('intended_interval_days', models.FloatField(help_text='The final post-fragile-cap interval (days) actually used.')),
                ('next_review_at', models.DateTimeField(help_text='The value just written to the progress row.')),
                ('jitter_offset_days', models.IntegerField(blank=True, help_text='Reserved for a future randomized-jitter feature; NULL for now.', null=True)),
                ('jitter_probability', models.FloatField(blank=True, help_text='Reserved for a future randomized-jitter feature; NULL for now.', null=True)),
                ('due_backlog_size', models.IntegerField(help_text="Count of the user's currently-due READY words at answer time.")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_decisions', to='vocabulary.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_decisions', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_decisions', to='vocabulary.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'word', 'answered_at'], name='vocabulary__user_id_09a8c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TypoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_text', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typo_attempts', to='vocabulary.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typo_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'answered_at'], name='vocabulary__user_id_d15ece_idx')],
            },
        ),
    ]
