# Generated by Django 5.2.7 on 2026-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0042_schedulingdecision_typoattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_serve_excluded',
            field=models.BooleanField(default=False, help_text='Admin flag-to-hide: never serve this question in practice.'),
        ),
        migrations.AddField(
            model_name='question',
            name='qa_checked_at',
            field=models.DateTimeField(blank=True, help_text='When item stats were last recomputed for this question.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='qa_flags',
            field=models.JSONField(blank=True, default=list, help_text='Item-quality flags, e.g. too_easy, too_hard, low_discrimination.'),
        ),
    ]
