# Generated by Django 5.2.7 on 2026-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_goal_max',
            field=models.IntegerField(default=50, help_text='Teacher-set maximum for the student daily goal.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_goal_min',
            field=models.IntegerField(default=20, help_text='Teacher-set minimum for the student daily goal.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_goal_prompt_date',
            field=models.DateField(blank=True, help_text='Date the daily goal adjustment prompt was last shown.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_question_limit',
            field=models.IntegerField(default=30, help_text='Teacher-set baseline daily practice goal for the student.'),
        ),
    ]
